apiVersion: v1
kind: Service
metadata:
  name: slurm-master-s1
spec:
  clusterIP: None
  selector:
    app: slurm-master-s1
    group: slurm-s1
  ports:
  - name: port6817
    port: 6817
    targetPort: 6817
    protocol: TCP
  - name: port6818
    port: 6818
    targetPort: 6818
    protocol: TCP
  - name: port6819
    port: 6819
    targetPort: 6819
    protocol: TCP
