apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurm-master-deployment
  labels:
    app: slurm-master
    group: slurm
spec:
  replicas: 1
  selector:
    matchLabels:
      group: slurm
      app: slurm-master
  template:
    metadata:
      name: slurm-master-pod
      labels:
        app: slurm-master
        group: slurm
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ip-172-31-19-24
            topologyKey: "kubernetes.io/hostname"
      hostname: slurm-master
      volumes:
        - name: slurm-lustre-vol-s1
          persistentVolumeClaim:
            claimName: lustre-local-storage-claim-s1
      containers:
        - name: master-container
          image: 041012/abhinav-master:v1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/lustre/s1"
              name: slurm-lustre-vol-s1
        - name: worker-container
          image: 041012/abhinav-node:v1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: "/lustre/s1"
              name: slurm-lustre-vol-s1
